### ISSUE TITLE
 LateInitializationError: Local 'cancelFunc' has not been initialized.

### ISSUE THREAD

**Issue by jinfagang** [MMMzq/bot_toast#145]
LateInitializationError: Local 'cancelFunc' has not been initialized.

**Comment by MMMzq** [comment]
If possible, please provide an example

**Comment by Nahrawene-ben-hmida** [comment]
Hello @MMMzq @lucasjinreal, 

I'm encountering the same issue, and it's critical for our app. Here's the stack trace from Sentry:  
![image](https://github.com/user-attachments/assets/1e011481-abe6-401b-91d1-848ed63fa781)
**LateError**  
`LateInitializationError: Local 'cancelFunc' has not been initialized.`  

- **internal_patch.dart**: `LateError._throwLocalNotInitialized` at line 190  
- **toast.dart**: `BotToast.showEnhancedWidget.<fn>` within `bot_toast`  

Let me know if you need further details!

**Comment by mfurkanyuceal** [comment]
For anyone finding this from a crash report: this is fixed in #185, with the root cause written up there and in #175.

The reason no one could produce a repro here is that the failure is not at the call site — `dismissFunc` is registered with the duration timer and the navigator observer before `cancelFunc` is assigned, so the error surfaces seconds later from an async callback, with no app frames in the stack. Pumping an app without `BotToastInit()` and then advancing past the toast duration reproduces it deterministically.
