### ISSUE TITLE
Failed assertion: line 10 pos 10: '_key?.currentState != null': is not true.

### ISSUE THREAD

**Issue by dufei816** [MMMzq/bot_toast#70]
我的界面都是StatelessWidget，刷新用Provider控制。
这种情况有处理方式吗？

**Comment by MMMzq** [comment]
能做一个简单复现的demo吗?这样我也能快速定位到问题,请理解.

并且请按照下面的格式填写一下必要内容:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**
Add any other context about the problem here.

**Comment by DTharaka** [comment]
Is there a solution for this issue?

**Comment by zlyBear** [comment]
> Is there a solution for this issue?

maybe you should use BotToastInit() in main.dart
