### ISSUE TITLE
bot_toast cause the SnackBar can not work?

### ISSUE THREAD

**Issue by zxl777** [MMMzq/bot_toast#76]
Scaffold.of(context).showSnackBar(SnackBar(content: Text("Copied")));

Do nothing.

**Comment by MMMzq** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**
Add any other context about the problem here.
