### ISSUE TITLE
Android 平台浏览器toast换行后，最后一行中文显示不全(官方bug)

### ISSUE THREAD

**Issue by lyf571321556** [MMMzq/bot_toast#80]
bot_toast: ^3.0.4
![image](https://user-images.githubusercontent.com/2295872/93560196-2d708600-f9b4-11ea-9360-f60318078534.png)

**Comment by MMMzq** [comment]
![图片](https://user-images.githubusercontent.com/28224568/93562235-35cac000-f9b8-11ea-9287-4c24ce82e7f0.PNG)

#### 1.如果时浏览器平台(暂不提供bug fix)

#### 2. 请按下面的表单提供相关信息

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (please complete the following information):**
 - Flutter Version: [e.g. v1.5.0]
 - OS: [e.g. iOS/Android]
 - BotToast Version : [e.g. 0.3.0]

**Additional context**
Add any other context about the problem here.

**Comment by lyf571321556** [comment]
已经修复，抽空发个pr给你！

**Comment by MMMzq** [comment]
好的谢谢 ：）
